/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.10 ../public/desktop_pc/desktop.gltf -T -i -s --precision 4 
Files: ../public/desktop_pc/desktop.gltf [1.48MB] > desktop-transformed.glb [8.95MB] (-504%)
*/

import React, { useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export function Model(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/desktop-transformed.glb')
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="RootNode001" position={[-0.1672, 0.4252, 3.4946]} rotation={[-3.1054, 0.2047, -3.0657]} scale={0.1324}>
          <group name="Bubbles32" />
        </group>
        <mesh name="GP_Layer" castShadow receiveShadow geometry={nodes.GP_Layer.geometry} material={materials.PaletteMaterial001} position={[3.2286, -0.2951, -11.2273]} />
        <mesh name="aorus_case_fans_aorus_case_fans_0" castShadow receiveShadow geometry={nodes.aorus_case_fans_aorus_case_fans_0.geometry} material={materials['Material.074_0']} position={[0.8959, 2.8868, -3.5542]} rotation={[0, Math.PI / 2, 0]} scale={1.0852} />
        <mesh name="aorus_logotranspa_aorus_logotranspa_0" castShadow receiveShadow geometry={nodes.aorus_logotranspa_aorus_logotranspa_0.geometry} material={materials['Material.074_24']} position={[-1.8243, 1.817, -3.1585]} scale={[0.0865, 0.0865, 0.0909]} />
        <mesh name="bg2_bg2_0" castShadow receiveShadow geometry={nodes.bg2_bg2_0.geometry} material={materials['Material.074_29']} position={[-1.5371, 1.9492, 0.8303]} rotation={[1.572, -1.4415, 1.5668]} scale={1.1303} />
        <mesh name="Cube_Material_0" castShadow receiveShadow geometry={nodes.Cube_Material_0.geometry} material={materials.Wood} position={[-0.6102, -0.0056, 1.5609]} rotation={[-Math.PI / 2, 0, Math.PI]} scale={[-3.6895, 7.3164, 0.2598]} />
        <mesh name="Cube004_Material002_0" castShadow receiveShadow geometry={nodes.Cube004_Material002_0.geometry} material={materials['Material.002']} position={[-1.4874, 1.8097, 2.9925]} rotation={[-Math.PI / 2, -0.0698, Math.PI / 2]} scale={[1.676, 0.1779, 1.935]} />
        <mesh name="Cube015_Material016_0" castShadow receiveShadow geometry={nodes.Cube015_Material016_0.geometry} material={materials['Material.074_1']} position={[-1.6545, 2.2412, -4.4084]} rotation={[-Math.PI / 2, 0, Math.PI]} scale={[-0.8937, 0.007, 1.0643]} />
        <mesh name="Cube025_Material023_0" castShadow receiveShadow geometry={nodes.Cube025_Material023_0.geometry} material={materials['Material.023']} position={[-1.6545, 2.2412, -4.4084]} rotation={[-Math.PI / 2, 0, Math.PI]} scale={[-0.8937, 0.007, 1.0643]} />
        <mesh name="Cube026_Material024_0" castShadow receiveShadow geometry={nodes.Cube026_Material024_0.geometry} material={materials['Material.024']} position={[-1.6545, 2.2412, -4.4084]} rotation={[-Math.PI / 2, 0, Math.PI]} scale={[-0.8937, 0.007, 1.0643]} />
        <mesh name="Cube027_Material008_0" castShadow receiveShadow geometry={nodes.Cube027_Material008_0.geometry} material={materials['Material.074_6']} position={[-0.9641, 2.7096, -4.3093]} rotation={[-Math.PI / 2, 0, 0]} scale={[-0.0151, 0.1092, 0.4429]} />
        <mesh name="Cube028_Material026_0" castShadow receiveShadow geometry={nodes.Cube028_Material026_0.geometry} material={materials['Material.074_7']} position={[-0.9571, 2.7096, -4.3241]} rotation={[-Math.PI / 2, 0, 0]} scale={[-0.0105, 0.0973, 0.4441]} />
        <mesh name="Cube045_Material027_0" castShadow receiveShadow geometry={nodes.Cube045_Material027_0.geometry} material={materials['Material.074_8']} position={[-2.1214, 0.794, -2.9823]} rotation={[-Math.PI / 2, 0, 0]} scale={[0.3548, 0.0517, 0.2057]} />
        <mesh name="Cube048_Material035_0" castShadow receiveShadow geometry={nodes.Cube048_Material035_0.geometry} material={materials['Material.074_15']} position={[-1.6135, 2.6824, -3.6817]} rotation={[-Math.PI / 2, 0, 0]} scale={[0.1744, 0.3941, 0.4007]} />
        <mesh name="Cube049_Material040_0" castShadow receiveShadow geometry={nodes.Cube049_Material040_0.geometry} material={materials['Material.074_16']} position={[-1.6135, 2.6824, -3.6817]} rotation={[-Math.PI / 2, 0, 0]} scale={[0.1744, 0.3941, 0.4007]} />
        <mesh name="Cube057_Material059_0" castShadow receiveShadow geometry={nodes.Cube057_Material059_0.geometry} material={materials['Material.074_22']} position={[-1.2722, 2.0008, -3.7056]} rotation={[-Math.PI / 2, 0, 0]} scale={[1.2806, 0.5244, 0.1267]} />
        <mesh name="Cube058_Material063_0" castShadow receiveShadow geometry={nodes.Cube058_Material063_0.geometry} material={materials['Material.074_23']} position={[-1.2259, 2.1371, -3.7043]} rotation={[-Math.PI / 2, 0, 0]} scale={[1.3326, 0.545, 0.0081]} />
        <mesh name="Cube075_Material086_0" castShadow receiveShadow geometry={nodes.Cube075_Material086_0.geometry} material={materials['Material.074_26']} position={[-2.5801, 1.9551, -3.7151]} rotation={[-Math.PI / 2, 0, 0]} scale={[0.0116, 0.5244, 0.1774]} />
        <mesh name="Cylinder005_Material041_0" castShadow receiveShadow geometry={nodes.Cylinder005_Material041_0.geometry} material={materials['Material.074_17']} position={[-1.6114, 2.6866, -3.6902]} rotation={[-Math.PI / 2, Math.PI / 2, 0]} scale={[0.3271, 0.3271, 0.3421]} />
        <mesh name="Cylinder006_Material050_0" castShadow receiveShadow geometry={nodes.Cylinder006_Material050_0.geometry} material={materials['Material.074_19']} position={[-2.0945, 1.8462, -3.701]} rotation={[-Math.PI / 2, 0, 0]} scale={[0.3635, 0.3822, 0.1057]} />
        <mesh name="Cylinder007_Material051_0" castShadow receiveShadow geometry={nodes.Cylinder007_Material051_0.geometry} material={materials['Material.074_20']} position={[-1.2444, 1.8462, -3.701]} rotation={[-Math.PI / 2, 0, 0]} scale={[0.3635, 0.3822, 0.1057]} />
        <mesh name="gallerymodel_gallerymodel_0" castShadow receiveShadow geometry={nodes.gallerymodel_gallerymodel_0.geometry} material={materials['Material.074_28']} position={[-1.4204, 1.6481, 5.9608]} rotation={[0.4412, -1.2842, 0.4408]} scale={0.8069} />
        <mesh name="gigabyte-logo_gigabyte-logo_0" castShadow receiveShadow geometry={nodes['gigabyte-logo_gigabyte-logo_0'].geometry} material={materials['Material.074_31']} position={[-1.6154, 4.4945, 0.8208]} rotation={[1.5708, -1.501, 1.5708]} scale={0.2369} />
        <mesh name="IOSHIELD_IOSHIELD_0" castShadow receiveShadow geometry={nodes.IOSHIELD_IOSHIELD_0.geometry} material={materials['Material.074_3']} position={[-2.5969, 2.848, -4.2249]} rotation={[Math.PI / 2, -Math.PI / 2, 0]} scale={[0.2648, 0.3086, 0.3183]} />
        <mesh name="maxresdefault_(1)_maxresdefault_(1)_0" castShadow receiveShadow geometry={nodes['maxresdefault_(1)_maxresdefault_(1)_0'].geometry} material={materials['Material.074_10']} position={[0.8771, 0.8361, -3.5531]} rotation={[0, Math.PI / 2, 0]} scale={0.3941} />
        <mesh name="metal-mesh-500x500_metal-mesh-500x500_0" castShadow receiveShadow geometry={nodes['metal-mesh-500x500_metal-mesh-500x500_0'].geometry} material={materials['Material.074_5']} position={[-0.4231, 3.5698, -3.5416]} rotation={[Math.PI / 2, 0, Math.PI]} scale={[1, 1.337, 1]} />
        <mesh name="MOBOAORUSORANGETRANS_MOBOAORUSORANGETRANS_0" castShadow receiveShadow geometry={nodes.MOBOAORUSORANGETRANS_MOBOAORUSORANGETRANS_0.geometry} material={materials['Material.074_4']} position={[-2.3559, 2.8775, -4.2392]} rotation={[0, 0, 0.6506]} scale={0.0634} />
        <mesh name="MY_SCREEN_MY_SCREEN_0" castShadow receiveShadow geometry={nodes.MY_SCREEN_MY_SCREEN_0.geometry} material={materials['Material.074_30']} position={[-1.3618, 3.0013, 3.0041]} rotation={[-Math.PI / 2, 1.501, Math.PI / 2]} scale={[3.3162, 3.4807, 3.3162]} />
        <mesh name="NVIDIA_LOGO_NVIDIA_LOGO_0" castShadow receiveShadow geometry={nodes.NVIDIA_LOGO_NVIDIA_LOGO_0.geometry} material={materials['Material.074_12']} position={[0.0059, 0.7043, -2.8907]} scale={0.4519} />
        <mesh name="Object_101_Material067_0" castShadow receiveShadow geometry={nodes.Object_101_Material067_0.geometry} material={materials['Material.074_36']} position={[1.4771, 0.326, 4.0309]} rotation={[-Math.PI / 2, -1.4805, Math.PI / 2]} scale={0.9141} />
        <mesh name="Object_103_Material070_0" castShadow receiveShadow geometry={nodes.Object_103_Material070_0.geometry} material={materials['Material.074_39']} position={[1.4771, 0.326, 4.0309]} rotation={[-Math.PI / 2, -1.4805, Math.PI / 2]} scale={0.9141} />
        <mesh name="Object_105_Tasten_2_0" castShadow receiveShadow geometry={nodes.Object_105_Tasten_2_0.geometry} material={materials.Tasten_2} position={[1.4771, 0.326, 4.0309]} rotation={[-Math.PI / 2, -1.4805, Math.PI / 2]} scale={0.9141} />
        <mesh name="Object_109_Material069_0" castShadow receiveShadow geometry={nodes.Object_109_Material069_0.geometry} material={materials['Material.074_38']} position={[1.4771, 0.326, 4.0309]} rotation={[-Math.PI / 2, -1.4805, Math.PI / 2]} scale={0.9141} />
        <mesh name="Object_113_Material068_0" castShadow receiveShadow geometry={nodes.Object_113_Material068_0.geometry} material={materials['Material.074_37']} position={[1.4771, 0.326, 4.0309]} rotation={[-Math.PI / 2, -1.4805, Math.PI / 2]} scale={0.9141} />
        <mesh name="Object_115_Material057_0" castShadow receiveShadow geometry={nodes.Object_115_Material057_0.geometry} material={materials['Material.074_33']} position={[1.4771, 0.326, 4.0309]} rotation={[-Math.PI / 2, -1.4805, Math.PI / 2]} scale={0.9141} />
        <mesh name="Object_121_Material066_0" castShadow receiveShadow geometry={nodes.Object_121_Material066_0.geometry} material={materials['Material.074_35']} position={[1.4771, 0.326, 4.0309]} rotation={[-Math.PI / 2, -1.4805, Math.PI / 2]} scale={0.9141} />
        <mesh name="Object_131_Material060_0" castShadow receiveShadow geometry={nodes.Object_131_Material060_0.geometry} material={materials['Material.074_34']} position={[1.4771, 0.326, 4.0309]} rotation={[-Math.PI / 2, -1.4805, Math.PI / 2]} scale={0.9141} />
        <mesh name="Object_137_Material005_0" castShadow receiveShadow geometry={nodes.Object_137_Material005_0.geometry} material={materials['Material.074_32']} position={[1.4771, 0.326, 4.0309]} rotation={[-Math.PI / 2, -1.4805, Math.PI / 2]} scale={0.9141} />
        <mesh name="Object_782_OnTheFly-bg_0" castShadow receiveShadow geometry={nodes['Object_782_OnTheFly-bg_0'].geometry} material={materials['Material.074_40']} position={[1.016, 0.4062, 2.4401]} rotation={[-Math.PI / 2, 0.0777, Math.PI / 2]} scale={0.2189} />
        <mesh name="Plane_Material053_0" castShadow receiveShadow geometry={nodes.Plane_Material053_0.geometry} material={materials['Material.074_21']} position={[1.1718, 0.256, -0.095]} rotation={[-1.5706, 0.0041, -1.5949]} scale={[1.2673, 1.0234, 0.9861]} />
        <mesh name="psuback_psuback_0" castShadow receiveShadow geometry={nodes.psuback_psuback_0.geometry} material={materials['Material.074_13']} position={[-2.6027, 0.7797, -3.5275]} rotation={[0, Math.PI / 2, 0]} scale={0.5949} />
        <mesh name="rgb-hdd-cover-aorus-v1_rgb-hdd-cover-aorus-v1_0" castShadow receiveShadow geometry={nodes['rgb-hdd-cover-aorus-v1_rgb-hdd-cover-aorus-v1_0'].geometry} material={materials['Material.074_9']} position={[-0.9348, 0.8317, -2.888]} scale={0.3694} />
        <mesh name="test-aorus-m2-souris-aorus-rgb2_test-aorus-m2-souris-aorus-rgb2" castShadow receiveShadow geometry={nodes['test-aorus-m2-souris-aorus-rgb2_test-aorus-m2-souris-aorus-rgb2'].geometry} material={materials['Material.074_18']} position={[-1.1585, 1.5075, -4.3522]} scale={0.3519} />
        <mesh name="usb_usb_0" castShadow receiveShadow geometry={nodes.usb_usb_0.geometry} material={materials['Material.074_14']} position={[0.7047, 3.5715, -2.8969]} rotation={[-Math.PI / 2, 0, Math.PI / 2]} scale={0.0734} />
        <group name="Magic_Potion_Magic_Potion1_0" position={[-0.7456, 0.4697, 3.1365]} rotation={[-3.1054, 0.2047, -3.0657]} scale={0.1324}>
          <mesh name="Magic_Potion_Magic_Potion1_0_1" castShadow receiveShadow geometry={nodes.Magic_Potion_Magic_Potion1_0_1.geometry} material={materials.Magic_Potion1} />
          <mesh name="Magic_Potion_Magic_Potion1_0_2" castShadow receiveShadow geometry={nodes.Magic_Potion_Magic_Potion1_0_2.geometry} material={materials.Algae} />
          <mesh name="Magic_Potion_Magic_Potion1_0_3" castShadow receiveShadow geometry={nodes.Magic_Potion_Magic_Potion1_0_3.geometry} material={materials.Mouth_bottle2} />
          <mesh name="Magic_Potion_Magic_Potion1_0_4" castShadow receiveShadow geometry={nodes.Magic_Potion_Magic_Potion1_0_4.geometry} material={materials.Plug1} />
          <mesh name="Magic_Potion_Magic_Potion1_0_5" castShadow receiveShadow geometry={nodes.Magic_Potion_Magic_Potion1_0_5.geometry} material={materials.Liquid1} />
          <mesh name="Magic_Potion_Magic_Potion1_0_6" castShadow receiveShadow geometry={nodes.Magic_Potion_Magic_Potion1_0_6.geometry} material={materials.Upper_Rope} />
          <mesh name="Magic_Potion_Magic_Potion1_0_7" castShadow receiveShadow geometry={nodes.Magic_Potion_Magic_Potion1_0_7.geometry} material={materials.Central_Rope} />
          <mesh name="Magic_Potion_Magic_Potion1_0_8" castShadow receiveShadow geometry={nodes.Magic_Potion_Magic_Potion1_0_8.geometry} material={materials.Central_Rope_copy1} />
          <mesh name="Magic_Potion_Magic_Potion1_0_9" castShadow receiveShadow geometry={nodes.Magic_Potion_Magic_Potion1_0_9.geometry} material={materials.Central_Rope_copy3} />
          <mesh name="Magic_Potion_Magic_Potion1_0_10" castShadow receiveShadow geometry={nodes.Magic_Potion_Magic_Potion1_0_10.geometry} material={materials.Top_Rope} />
          <mesh name="Magic_Potion_Magic_Potion1_0_11" castShadow receiveShadow geometry={nodes.Magic_Potion_Magic_Potion1_0_11.geometry} material={materials.Central_Rope_copy4} />
          <mesh name="Magic_Potion_Magic_Potion1_0_12" castShadow receiveShadow geometry={nodes.Magic_Potion_Magic_Potion1_0_12.geometry} material={materials.Central_Rope_copy5} />
          <mesh name="Magic_Potion_Magic_Potion1_0_13" castShadow receiveShadow geometry={nodes.Magic_Potion_Magic_Potion1_0_13.geometry} material={materials.Central_Rope_copy6} />
          <mesh name="Magic_Potion_Magic_Potion1_0_14" castShadow receiveShadow geometry={nodes.Magic_Potion_Magic_Potion1_0_14.geometry} material={materials.Central_Rope_copy7} />
          <mesh name="Magic_Potion_Magic_Potion1_0_15" castShadow receiveShadow geometry={nodes.Magic_Potion_Magic_Potion1_0_15.geometry} material={materials.Bottom_Rope} />
          <mesh name="Magic_Potion_Magic_Potion1_0_16" castShadow receiveShadow geometry={nodes.Magic_Potion_Magic_Potion1_0_16.geometry} material={materials.Central_Rope_copy2} />
          <mesh name="Magic_Potion_Magic_Potion1_0_17" castShadow receiveShadow geometry={nodes.Magic_Potion_Magic_Potion1_0_17.geometry} material={materials.Bubbles} />
        </group>
        <mesh name="Object_7" castShadow receiveShadow geometry={nodes.Object_7.geometry} material={materials.PaletteMaterial002} position={[-0.8716, 0.2178, 2.6438]} rotation={[-Math.PI / 2, 0, 1.546]} scale={0.227} />
        <mesh name="pPlatonic1_lambert2_0" castShadow receiveShadow geometry={nodes.pPlatonic1_lambert2_0.geometry} material={materials.lambert2} position={[-0.9943, 1.1236, 3.5858]} rotation={[-Math.PI, 0, 0]} scale={[-0.1866, 0.1866, 0.1866]} />
        <mesh name="Book_lambert15_0" castShadow receiveShadow geometry={nodes.Book_lambert15_0.geometry} material={materials.lambert15} position={[-1.4723, 0.4265, 7.0792]} rotation={[Math.PI, 0.9193, -Math.PI]} scale={0.0183} />
        <mesh name="Object_4001" castShadow receiveShadow geometry={nodes.Object_4001.geometry} material={materials.bake} position={[-1.4637, 0.7369, 7.0553]} rotation={[3.1107, 1.3027, -3.1394]} scale={1.227} />
        <group name="Mouse" position={[1.3346, 0.2355, -0.2134]} rotation={[-3.1222, -1.4797, -3.1249]} scale={9.4005}>
          <mesh name="Plane004" castShadow receiveShadow geometry={nodes.Plane004.geometry} material={materials['Rough Plastic Insigna color']} />
          <mesh name="Plane004_1" castShadow receiveShadow geometry={nodes.Plane004_1.geometry} material={materials['Rough Plastic']} />
          <mesh name="Plane004_2" castShadow receiveShadow geometry={nodes.Plane004_2.geometry} material={materials.Color} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/desktop-transformed.glb')
